namespace DreamBig.SourceGen.Dapper.Attributes;

/// <summary>
/// Marks an entity property as the primary key.
/// </summary>
[AttributeUsage(AttributeTargets.Property, Inherited = false)]
public sealed class DbKeyAttribute : Attribute
{
    /// <summary>
    /// Gets or sets a value indicating whether the key value is generated by the database.
    /// When <see langword="false"/>, the key column is included in generated INSERT statements
    /// so client-assigned keys (for example GUIDs or natural keys) can be inserted.
    /// Defaults to <see langword="true"/>.
    /// </summary>
    public bool Generated { get; set; } = true;
}
